id: 987cd54a522e
kind: direct
title: New chat
created_by: horst.schwarz@joydev.com
created: 2026-07-07T22:17:39.226502696Z
updated: 2026-07-12T10:36:22.541239448Z
participants:
- horst.schwarz@joydev.com
messages: []
