id: e1111b2724fd
kind: direct
title: New chat
created_by: horst.schwarz@joydev.com
created: 2026-07-10T10:16:54.843883955Z
updated: 2026-07-10T10:17:22.809243284Z
participants:
- horst.schwarz@joydev.com
messages: []
