id: 1554dcdc2396
kind: direct
title: New chat
created_by: horst.schwarz@joydev.com
created: 2026-07-12T10:39:44.646000471Z
updated: 2026-07-12T10:40:00.702682631Z
participants:
- horst.schwarz@joydev.com
messages: []
