id: c7ad3be2e5c8
kind: direct
title: New chat
created_by: horst.schwarz@joydev.com
created: 2026-07-07T22:17:50.956330089Z
updated: 2026-07-07T22:17:50.956330089Z
participants:
- horst.schwarz@joydev.com
messages: []
