id: da18eec2db49
kind: direct
title: New chat
created_by: horst.schwarz@joydev.com
created: 2026-07-08T04:43:41.319647720Z
updated: 2026-07-08T04:43:58.880267999Z
participants:
- horst.schwarz@joydev.com
messages: []
